const zh = {
  // ─── 通用 ────────────────────────────────────────
  common: {
    loading: '加载中...',
    retry: '重试',
    back: '返回',
    confirm: '确认',
    cancel: '取消',
    save: '保存',
    refresh: '🔄 刷新',
    share: '📤 分享',
    export: '📊 导出报告',
    noData: '暂无数据',
    langToggle: 'EN',
  },

  // ─── 首页 ─────────────────────────────────────────
  landing: {
    title: '智能皮肤检测',
    subtitle: 'AI 科技，精准分析，为您定制护肤方案',
    startBtn: '📷 开始检测',
    historyBtn: '📋 历史记录',
    profileBtn: '👤 个人中心',
    tipText: '💡 使用提示：请确保光线充足，面部正对摄像头，保持表情自然',
    cooldown: (m: number, s: string) => `冷却中，还需 ${m}:${s}`,
    // 隐私弹窗
    privacyTitle: '使用前请阅读',
    privacyFuncTitle: '📋 功能说明',
    privacyFuncDesc: '本功能将请求您的相机或相册权限，以获取您拍摄或选择的照片，用于分析皮肤纹理状态（水分、油脂、毛孔、敏感度等维度），为您提供个性化护肤建议。',
    privacyDataTitle: '🔒 数据处理说明',
    privacyDataItem1: '• 照片仅用于本次皮肤状态分析',
    privacyDataItem2: '• 分析完成后，图片即时删除，不做存储',
    privacyDataItem3: '• 不采集、不识别、不存储任何生物特征信息',
    privacyDataItem4: '• 不会将数据共享给任何第三方',
    privacyFooter: '点击「同意」即表示您已阅读并同意上述说明\n拒绝授权不影响小程序其他功能的使用',
    privacyAgree: '同意',
    privacyDisagree: '不同意',
    privacyDeniedToast: '您拒绝了授权，无法使用检测功能',
  },

  // ─── 拍照页 ───────────────────────────────────────
  camera: {
    flashOff: '闪光关',
    flashOn: '闪光开',
    flashTorch: '常亮',
    scanning: '皮肤检测',
    photoFail: '拍照失败，请重试',
    photoError: '获取图片失败',
    cooldown: (m: number, s: string) => `冷却中，还需 ${m}:${s}`,
    countdownBadge: (s: number) => `${s} 秒后拍照`,
    keepStill: '请保持面部不动',
    alignFace: '请将面部对准椭圆框',
    album: '相册',
    flip: '翻转',
  },

  // ─── 分析中 ───────────────────────────────────────
  analyzing: {
    title: '正在分析...',
    subtitle: 'AI 正在识别您的皮肤状态，请稍候',
    steps: ['图像预处理', '特征提取', '皮肤评估', '生成报告'],
    failTitle: '分析失败',
    failMsg: '皮肤分析失败，请重试',
    retryBtn: '重新检测',
    notFound: '未找到检测结果',
    // Preview section
    previewDone: '分析完成！',
    previewReportReady: '您的肤质报告已生成',
    previewMoisture: '水分',
    previewOiliness: '油性',
    previewSensitivity: '敏感度',
    previewSkinType: '皮肤类型',
    previewConcerns: '主要问题',
    autoJump: (s: number) => `${s} 秒后自动跳转`,
    // Step status texts
    stepActivating: '准备分析中，请稍候...',
    stepAnalyzing: 'AI分析中，请稍候...',
    stepProcessing: '深度分析中，请稍候...',
    stepPreviewReady: '报告已生成',
    stepComplete: '分析完成',
    stepFaceAnalyzing: '面部分析中',
    stepDefault: '分析中...',
    // Buttons
    viewReport: '查看报告',
    jumpNow: '立即跳转',
    cancelBtn: '取消',
    cancelTitle: '提示',
    cancelContent: '分析正在进行中，确定要取消吗？',
    // Save
    loginToSave: '请先登录以保存记录',
    recordSaved: '记录已保存',
    saveFail: (msg: string) => `保存失败: ${msg}`,
    saveNetworkFail: '保存失败，请检查网络',
    analysisFail: '分析失败',
  },

  // ─── 结果页 ───────────────────────────────────────
  result: {
    notFound: '未找到检测结果',
    excellent: '优秀',
    good: '良好',
    needsWork: '需改善',
    skinScore: '皮肤综合评分',
    skinType: '皮肤类型',
    concerns: '主要问题',
    radarTitle: '皮肤状态雷达图',
    moisture: '水分',
    oiliness: '油性',
    sensitivity: '敏感度',
    acne: '痘痘',
    wrinkles: '皱纹',
    spots: '色斑',
    pores: '毛孔',
    blackheads: '黑头',
    recommendations: '护肤建议',
    reDetect: '🔄 重新检测',
    viewDetail: '查看详细报告',
    saveResult: '💾 保存结果',
    saveSuccess: '结果已保存到历史记录',
    loadError: '加载结果失败',
  },

  // ─── 历史记录 ─────────────────────────────────────
  history: {
    title: '肤质档案',
    subtitle: '管理您的皮肤检测记录',
    searchPlaceholder: '搜索档案ID或皮肤类型',
    filterAll: '全部',
    filterDry: '干性',
    filterOily: '油性',
    filterComb: '混合',
    filterSens: '敏感',
    viewTimeline: '时间轴',
    viewCalendar: '日历',
    viewTrend: '趋势图',
    exportReport: '📊 导出报告',
    shareBtn: '📤 分享',
    syncTip: '检测数据已同步到云端，可在多设备查看',
    syncBtn: '查看同步',
    skinTrend: '皮肤指标趋势',
    totalCount: (n: number) => `共 ${n} 次检测`,
    moistureTrend: '水分',
    oilTrend: '油性',
    sensitivityTrend: '敏感度',
    noRecords: '暂无检测记录',
    startFirst: '开始第一次检测',
    // 时间范围
    timeAll: '全部时间',
    time7d: '最近7天',
    time30d: '最近30天',
    time90d: '最近90天',
    // 对比
    compareMax: '最多选择2条记录进行对比',
    compareSelect: '请选择2条记录进行对比',
    compareBtn: '对比',
    selectedCount: (n: number) => `已选择 ${n} 条记录`,
    // 操作
    copyId: '复制ID',
    copyIdSuccess: '档案编号已复制',
    delete: '删除',
    deleteTitle: '确认删除',
    deleteContent: (id: number) => `确定要删除档案 #${id} 吗？`,
    deleteSuccess: '删除成功',
    deleteFail: '删除失败',
    // 状态
    loginRequired: '请先登录以查看您的检测记录',
    loginExpired: '登录已过期，请重新登录',
    loadFail: '加载失败',
    retrying: '加载失败，正在重试...',
    networkError: '加载失败，请检查网络',
    refreshSuccess: (n: number) => `刷新成功，共 ${n} 条记录`,
    searchNoResult: '未找到匹配的档案',
    onlyShow10: '仅显示最近10次检测数据',
    // 档案卡片
    recordId: (id: number) => `档案 #${id}`,
    scoreUnit: '分',
    // 导出/分享
    noDataExport: '暂无数据可导出',
    exportLoading: '生成报告中...',
    exportSuccess: '报告已保存到相册',
    exportFail: '导出失败',
    noDataShare: '暂无数据可分享',
    shareLoading: '生成分享图片...',
    shareSuccess: '分享图片已生成',
    shareContent: '图片已保存到相册，您可以到朋友圈发布',
    shareFail: '生成失败',
    // 日历
    calendarYearMonth: (y: number, m: number) => `${y}年${m}月`,
    // canvas 文字
    canvasReportTitle: '皮肤检测报告',
    canvasGeneratedAt: (date: string) => `生成时间: ${date}`,
    canvasLatestResult: '最新检测结果',
    canvasSkinType: (type: string) => `皮肤类型: ${type}`,
    canvasScore: (score: number) => `综合评分: ${score}分`,
    canvasMoisture: (v: number) => `水分: ${v}%`,
    canvasOiliness: (v: number) => `油性: ${v}%`,
    canvasSensitivity: (v: number) => `敏感度: ${v}%`,
    canvasHistoryTrend: '历史趋势',
    canvasMoistureLabel: '水分',
    canvasShareTitle: '我的皮肤报告',
    canvasShareSkinType: (type: string) => `皮肤类型: ${type}`,
    canvasShareMoisture: (v: number) => `水分: ${v}%`,
    canvasShareOiliness: (v: number) => `油性: ${v}%`,
    canvasShareSensitivity: (v: number) => `敏感度: ${v}%`,
    canvasShareQrTip: '扫码查看详细报告',
    // 登录提示
    goLogin: '去登录',
    startDetect: '开始检测',
  },

  // ─── 个人中心 ─────────────────────────────────────
  profile: {
    title: '我的',
    editProfile: '完善个人信息',
    avatarFromAlbum: '相册选择',
    avatarFromWeChat: '微信头像',
    nicknameLabel: '昵称',
    nicknameInput: '输入昵称',
    cancelBtn: '取消',
    saveBtn: '保存',
    detectCount: '检测次数',
    detectUnit: '次',
    memberLevel: '会员等级',
    premium: '高级会员',
    normal: '普通会员',
    settings: '设置',
    notLoggedIn: '未登录',
    loginTip: '登录后可查看检测记录和个性化推荐',
    loggingIn: '登录中...',
    loginBtn: '微信一键登录',
    logoutBtn: '退出登录',
    logoutTitle: '提示',
    logoutContent: '确定要退出登录吗？',
    logoutSuccess: '已退出登录',
    loginSuccess: '登录成功',
    loginFail: '登录失败',
    nicknameRequired: '请输入昵称',
    saveSuccess: '保存成功',
    saveFail: '保存失败',
    startJourney: '开始您的皮肤检测之旅',
    editBtn: '编辑',
  },

  // ─── 商城 ────────────────────────────────────────
  mall: {
    title: '护肤商城',
    subtitle: '为您精选的护肤产品',
    addToCart: '加入购物车',
    buyNow: '立即购买',
    noProducts: '暂无推荐产品',
  },

  // ─── 产品推荐 ─────────────────────────────────────
  recommend: {
    title: '专属推荐',
    subtitle: '根据您的肤质定制推荐',
    basedOn: '基于最近检测结果',
    noRecommend: '暂无推荐',
    checkHistory: '请先完成皮肤检测',
  },

  // ─── 导航栏 ───────────────────────────────────────
  navbar: {
    home: '返回首页',
    back: '返回',
  },

  // ─── Tab Bar ──────────────────────────────────────
  tabbar: {
    home: '首页',
    history: '历史',
    profile: '我的',
  },
}

export type I18nKeys = typeof zh
export default zh
